title: Kyle Stevens
email: kstevens715@gmail.com
description: >
  I'm a software developer currently focusing on Ruby on Rails and JavaScript
  development.
baseurl: ""
url: "http://kstevens.org"
twitter_username: kste715
github_username:  kstevens715
markdown: kramdown
